#! /bin/bash

# Author:      Stefan Eng
# License:     GPL v3
# File:        functions
# Description:
#     Aggregates all the bash scripts into one file to be sourced

# Get the directory we are working in so we can source from anywhere
# From http://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Manually source the git_branch function
# TODO: Automate this for all *.sh files 
[[ -f $DIR/git_branch.sh ]] && . $DIR/git_branch.sh

unset DIR
unset SOURCE
